### ISSUE TITLE
How can we use this script to install open connect next to nginx on a subdomain?

### ISSUE THREAD

**Issue by rxmoein** [xhdix/openconnect-installer#2]
I have nginx running on my server and I want to have this service next to it on a subdomain, how is this possible?

**Comment by xhdix** [comment]
Only these changes are needed:
https://github.com/xhdix/openconnect-installer/compare/nginx-subdomain
(Not tested. I will be glad to know that it works as expected.)

But about changing the port*, consider this:
https://geneva.cs.umd.edu/posts/iran-whitelister/

[*]  Change 443 to 2083, cPanel default port.
